   language: python
   python:
        - "3.5"
   install:
        - pip install coveralls
   script:
        - python3 test_rpn.py
        - coverage run --source=home test_rpn.py test home
   after_success: coveralls

